### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by siegfried** [vorner/tuntap#3]
Hi,

Thanks for open sourcing this useful project. I want to discuss some changes to add OpenBSD support:

1. On OpenBSD, tun/tap devices are just like normal files to be opened. So I think no C code is needed to setup. However, according to the [manual](https://man.openbsd.org/tun.4), `Each packet read or written is prefixed with a tunnel header consisting of a 4-byte network byte order integer containing the address family.` So the `recv` and `send` functions must be different from the ones for Linux if we want the compatibility between them. How would you like to organize the different functions? Using macros like `#[cfg(target_os = "linux")]` I assume?
2. The packet info option is Linux specific. Shall we force to `IFF_NO_PI`?

I have a C project already working on Linux&OpenBSD. Here are the C code for [OpenBSD](https://github.com/siegfried/tuntap_port/blob/master/src/utuntap.c) and [Linux](https://github.com/siegfried/tuntap_port/blob/master/src/tuntap.c) for your consideration.

**Comment by vorner** [comment]
Hello

Honestly, I'm not quite sure.

First, I've done this mostly for fun and don't really pay much attention to this library. It doesn't really have many useful features, etc. Also I don't want to invest much time into support of another latform. I'm fine merging patches and reviewing, sure. But I don't have OpenBSD and I don't think the CI is set up for that platform either, so I wouldn't even know if some future change broke the support. Therefore, if you want it, the work would probably have to be done by you and you'd need to provide at least compilation CI + become some kind of platform maintainer (eg. making sure the platform stays alive over time).

Second, I would not like to lose one of the features on the platform I have (eg. the packet info before the packet). So forcing a non-default method seems wrong to me. Maybe not supporting the `fn new` and having only the `without_packet_info`? Or changing it to a single function with non-exhaustive enum and not having the packet info variant available on platforms that don't support them?

Currently you seem to have created completely different C file. The compilation can probably be chosen from the build.rs script. Are there any changes needed in the Rust code too? If so, I'd try to have them as minimal as possible and yes, these would be under some kind of `cfg` attributes. Maybe only platform dependant sub-functions or blocks?

Does that make sense?

**Comment by siegfried** [comment]
Sorry, I didn't make myself clear. I actually need a useful Tun/Tap library for my project. Instead of starting from scratch, I thought it would be better to help the existing one. I'll take care of the code to support OpenBSD and setup a CI environment. It would be great if you can review the PR and discuss the changes though.

I'm not sure about having only the `without_packet_info`. A unified interface seems better for cross-platform, right? Packet info is totally unknown to other OS. I'll ruminate on the single function with non-exhaustive enum way. Do you have any example how you would want it look like? Thanks.

**Comment by vorner** [comment]
> It would be great if you can review the PR and discuss the changes though.

Sure, I can help with that.

> Do you have any example how you would want it look like?

My idea for the interface would be something like this:

```rust
#[non_exhaustive]
pub enum PktMode {
    Bare,
    #[cfg(target_os = "linux")]
    WithPacketInfo,
}

impl Iface {
    pub fn new(name: &str, mode: Mode, pkt_mode: PktMode)
}
```

But seeing it written here, I'm not sure it's ergonomic, especially as other platforms don't have the use of the second parameter. Further alternatives:
* Builder pattern, eg. `Iface::new("tun0", Mode::Tun).with_packet_info().build()`.
* Use the bitflags crate and specify the flags, eg: `Iface::new("tun0", Mode::TUN | Mode::PKT_INFO)`. But that would have to check at runtime that you don't provide invalid mode (eg. you'd have to have exactly one of TUN/TAP).

**Comment by siegfried** [comment]
How about maintain a Trait like:

```rust
pub enum Mode {
    TUN,
    TAP
}

trait TunTap {
    fn open(mode: Mode, number: u8) -> File
}
```

And then implement the trait for `Iface` struct for different OSes with [`cfg_attr`](https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg_attr-attribute):

```rust
#[cfg_attr(linux, path = "linux.rs")]
#[cfg_attr(windows, path = "windows.rs")]
mod os;
```

The `open` function should setup a compatible Tun/Tap device between different OSes. To Linux, it means no packet info. On the other hand, a public function which turn on the packet info can be implemented in the Linux module alone, with warning messages. Or an `ioctl` function for each OS should work as well.

Also, implementing `std::io::Read` trait and `std::io::Write` trait for `Iface` instead of `send` and `recv` seems a better choice since a Tun/Tap device is very much a special file.

**Comment by vorner** [comment]
I believe a trait here would be counter-intuitive, as you would have to import the trait to work for you on the caller side. Or you mean the train only for local use? You don't need it. You can simply have a separate `fn open` for each OS, without a trait, either with or without modules. I'm also strongly against returning a `File`, see more below for why. 

You could have OS-specific module with `cfg_attr` allright, but I feel like the differences between OSes won't be as great to warrant completely different file and rewrite of everything. I'd prefer having as small changes in code as possible and have them inline instead of too much indirection.

I think on linux we still want to be able to *choose* if we want the packet info or not. And I don't think a warning message is in place there.

The perception of tun/tap device being a `File` in the rust's sense is IMO wrong. Files behave in a certain way ‒ they are continuous streams of bytes. They are seekable. They report to be always ready in select/poll/epoll. On the other hand, tun/tap devices are inherently message oriented (each separate packet is independent), they can be ready or not, can support async operations and are not seekable. What would `tun_iface.read_to_end(&mut buffer)` do? Join content of all the packets together? What happens if you write it to a `BufWriter`, which you have full right to do if it implements `Write`?

So I believe the `send`/`recv` interface is more appropriate. See for example the `UdpSocket` interface, it doesn't implement `Read` or `Write` either.

**Comment by siegfried** [comment]
Sorry, I made a mistake in the trait. The `open` function should return an `Iface`, which contains a File attribute in your code I believe, not a `File` directly.

```rust
pub enum Mode {
    TUN,
    TAP
}

trait TunTap {
    fn open(mode: Mode, number: u8) -> Iface
}
```

The trait was just a guarantee that each OS module has an `open` to return an `Iface` can talk to each other on different OSes. But you are right, we can check each OS module as well, and we'll need to even if each OS module has implemented the trait. Trust me that incompatible packets from the same library can be very painful for other devs. However, I don't mean to get rid of Linux packet info from the library. I just don't think it should default to having it and it would be nice to let the caller know the caution to use it. The function to turn the packet info on can be moved to the Linux module. Actually, on the contrary, I hope the library can do as much as C.

Think about this, to setup a Tun/Tap device you kinda do two same things on Linux/*BSD/macOS(not sure about Windows):

1. Call `open(path, opts)` to get a file descriptor. On Linux the path is `/dev/net/tun`, whereas on OpenBSD the path is `/dev/tun*` or `/dev/tap*`; others might either behave like Linux or OpenBSD.
2. Call `ioctl()` to configure it. This is where you set `IFF_NO_PI` on Linux. OpenBSD normally don't need to but `ioctl()` works on its Tun/Tap file descriptor as well if there are some special settings are needed. Others OSes should be the same.

So instead of a function like `with_packet_info` in Linux module, I was proposing some function more general like `ioctl()` for each OS.

Implementing `std::io::Read` and `std::io:Write` for `Iface` has nothing to do with the `File` type. Sorry again for my mistake in the code example. I'm thinking of this because:

1. On Linux/*BSD/macOS, you still use the same `open()/read()/write()` to operate either normal files or device files like Tun/Tap. I guess this has something to do with *Everything is a File*.
2. In order to prevent the additional bytes from OpenBSD Tun device (maybe macOS, too) making problems on Linux Tun devices, they should be skipped (yes, the compatibility again). In C, this was done by `readv()` and `writev()`; the counterparts in Rust are `read_vectored()` or `write_vectored()` provided by `Read` and `Write` traits, right?

I'm quite new to Rust. Please correct me if I'm wrong. `std::io::Read` and `std::io::Write` have nothing to do with seekablity and async operations, do they? I do agree with you that `tun_iface.read_to_end(&mut buffer)` is weird, and so is `tun_iface.read_to_string(&mut String)`. But as soon as they rely on `read()`, I'm not sure how wrong they can be. `read_to_end()` will be block or return an error(EAGAIN in C) just like `read()` anyway. The same goes to `Write`, I personally think `BufWriter` on an `Iface` is useless and I probably would never do that, but I don't know how wrong it can be. `recv()` cannot prevent incorrect bytes as well, right?

The UDP socket example kinda make sense, too. Do you have any idea to handle the OpenBSD issue? Thanks.

**Comment by siegfried** [comment]
Ah, never mind. I think I can still use `read_vectored` in `recv`.

**Comment by vorner** [comment]
I'm not sure if I'm getting you correctly. So you propose to open the interface, get a fully functional one and *then* modify it to have the packet info? While the C interface does allow that, and you maybe could switch it „in the middle“ of using the interface, it seems a bit weird to want to do that. I was thinking about the builder pattern because setting the mode is something user should do before starting to use it. Can it even be switched in a meaningful way once packets start coming in? Will the application know which packet has it switched already and which one is according to the old mode?

What do you mean, in the linux module? You mean a method that is available on linux but not on *BSD, that is internally implemented in a linux.rs but visible on the top-level Iface type from user point of view? That would probably be fine. I wouldn't like to expose a `linux` module (eg. `tuntap::linux`) with a stand-alone function.

**Comment by siegfried** [comment]
Let me explain in the PR. I'll add some tests first.

**Comment by siegfried** [comment]
FYI. I thought about the crate I want to use in my project again. It turned out the API I want to use is pretty low level. So I started this project. https://github.com/siegfried/utuntap
I think it's ok to close this issue now, otherwise, I can also make this crate cross-platform by introducing that one after I get more OSes supported. Thanks for your help so far.

**Comment by vorner** [comment]
OK, thanks. I'll close it for now, but if you ever feel like sending the pull request for this crate, I'll be happy to give it a review.
