### ISSUE TITLE
Is there a way to use a created TUN/TAP iface without creating it?

### ISSUE THREAD

**Issue by jethrosun** [vorner/tuntap#8]
Hi,

Very useful crate, thx! My questions is, is there a way to use a TUN/TAP interface directly? The interface is already created so I just want to access it.

**Comment by vorner** [comment]
Hello

TBH, I'm not sure. Well, I'm not _entirely_ sure in what exact situation you're. Like, there's an already named interface in the system and you want to open the existing one instead of creating a new one?

It's a long time since I last touched this crate, but I think just passing the name to the constructor might do the trick. If not, what would be the C calls you'd do to achieve the result?

**Comment by FlorianFreudiger** [comment]
Can confirm this already works.

You only have to be careful about matching some of the tuntap parameters, otherwise you may get invalid argument errors.
For example if the tuntap interface has been created with multiqueue, the ioctl call would presumably also need to pass `IFF_MULTI_QUEUE` (and the crate would need to support multiple queues)

**Comment by vorner** [comment]
I believe supporting multiple queues and other flags is probably a different use case than this one. I'm not against a pull request adding that, but I think I'll just close this issue in the meantime.
